### ISSUE TITLE
Install via Brew

### ISSUE THREAD

**Issue by tsykoduk** [hunleyd/gwt#5]
I'd like to be able to install this via brew

**Comment by hunleyd** [comment]
And I'd like Jenna Dewan to realize that Steve Kazee is not her soul mate and that I'm waiting for her :)

**Comment by hunleyd** [comment]
In all seriousness, I'm not sure how `brew` would edit your `.bashrc` or `.zshrc` to do the necessary `source` of this file. Or are you just wanting `brew` to install it and you'll do that part yourself?

**Comment by tsykoduk** [comment]
closed due to OP trolling
